(function(g){var window=this;'use strict';var X3=function(a){a.oa("cardstatechange",a.Ak()&&a.So()?1:0)},Y3=function(a,b){var c=g.$a(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},llb=function(a){var b=g.qs(a);
a=g.us(a);return new g.fs(b.x,b.y,a.width,a.height)},mlb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.UC(a,b,function(){g.VC(e);c.apply(a,arguments)},d)},a4=function(a){a=g.eb(a);
delete Z3[a];g.id(Z3)&&$3&&$3.stop()},olb=function(){$3||($3=new g.Qu(function(){nlb()},20));
var a=$3;a.isActive()||a.start()},nlb=function(){var a=g.jb();
g.Wc(Z3,function(b){plb(b,a)});
g.id(Z3)||olb()},b4=function(a,b,c,d){g.pv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},plb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;qlb(a,a.progress);1==a.progress?(a.j=0,a4(a),a.onFinish(),a.Wq()):a.isPlaying()&&a.lL()},qlb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},rlb=function(a,b){g.zb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},c4=function(a,b,c,d,e){b4.call(this,b,c,d,e);
this.element=a},slb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
c4.call(this,a,b,c,d,e)},tlb=function(a){return Math.pow(a,3)},ulb=function(a){return 3*a*a-2*a*a*a},vlb=function(a){g.H.call(this);
this.B=a||window;this.j=[]},d4=function(a){return a.baseUrl||null},e4=function(a,b){return g.ot(g.Ar(a,b),function(c){return!!c})},wlb=function(a,b,c){function d(sa){var la=sa.hovercardButton;
if(!la)return null;la=la.subscribeButtonRenderer;if(!la)return null;var ra=f(la.unsubscribedButtonText),ba=f(la.subscribedButtonText);if(la.subscribed){var U=f(la.subscriberCountWithUnsubscribeText);var Na=f(la.subscriberCountText)}else U=f(la.subscriberCountText),Na=f(la.subscriberCountWithSubscribeText);var y=null;if(sa.signinEndpoint){y=Y3(sa,"signinEndpoint","webNavigationEndpointData","url");if(!y){var Z,Va;y=null==(Va=g.R(null==(Z=la.signInEndpoint)?void 0:Z.commandMetadata,g.P2))?void 0:Va.url}if(!y)return null}return ra&&
(ba||y)?{subscribed:la.subscribed,subscribeText:ra,subscribeCount:U,unsubscribeText:ba,unsubscribeCount:Na,enabled:la.enabled,signinUrl:y,classic:sa.useClassicSubscribeButton}:null}
function e(sa){if(sa){var la=[],ra=sa.videoId;ra&&la.push("v="+ra);(ra=sa.playlistId)&&la.push("list="+ra);(sa=sa.startTimeSeconds)&&la.push("t="+sa);return"/watch?"+la.join("&")}}
function f(sa){if(!sa)return null;var la=sa.simpleText;return la?la:sa.runs?g.Ar(sa.runs,function(ra){return ra.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,B=null,F=null,G=null,I=null,L=null,P=null;if("VIDEO"===h)g.R(l,g.JG)?m=g.R(l,g.JG).url:(P=g.R(l,g.AT),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.R(l,g.JG)?m=g.R(l,g.JG).url:(P=g.R(l,g.AT),m=e(P)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=Y3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((G=Y3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=Y3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=Y3(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:null,
ka="";if(b.metadata){var ta=f(b.metadata);ta&&(ka=ta)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ka,callToAction:f(b.callToAction),yV:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,ND:p,playlistLength:t,channelId:v,subscribeButton:B,subscribersText:F,isSubscribe:x,targetUrl:m||null,D7:n,sessionData:X?{itct:X}:null,Vba:q,qC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:e4(b.impressionUrls||[],d4),q7:e4(b.hovercardShowUrls||[],d4),clickUrls:e4(l.loggingUrls||[],d4),visualElement:g.JF(b.trackingParams),productPrice:I,additionalFeesText:L,watchEndpoint:P||null}},xlb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:e4(a.impressionUrls||[],d4),elements:e4(a.elements||[],function(d,e){return wlb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.JF(a.trackingParams));return c},ylb=function(a){g.UV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.W=!0;this.K=0;a=a.U();this.Z=g.tS(a)||g.vS(a);this.events=new g.gL(this);g.J(this,this.events);this.events.T(this.player,g.uK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.vK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Zb);this.events.T(window,"focus",this.faa);this.load();var b=g.ef("STYLE");(g.Pe("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.sf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},zlb=function(a){return a.player.getVideoData().Hf?"current":a.Z?"new":"current"},f4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Alb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=xlb(f,zlb(a))));g4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.qx;d&&(c.postParams={ad_tracking:d});if(b=g.RSa(b))if(b=g.bo(b),b=g.$d(b))a.C=g.lC(b,c)},g4=function(a,b,c){c=void 0===c?!0:c;
a.player.yf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Blb(a);c=[];d=new g.tK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.S({I:"div",S:"ytp-ce-shadow"}),g.HU(a.player,a.B.element,4),a.D=new g.WG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Clb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.HU(a.player,f.element,4);var h=new g.tK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Dlb(a,f,e)}else g.PF(new g.kD("buildEndscreenElement null",
e))}a.player.qf(c);a.Zb()}},Blb=function(a){var b=g.KF(),c=g.LF();
c&&b&&a.endscreen.visualElement&&g.UB(g.XF)(void 0,c,b,a.endscreen.visualElement)},Clb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.qC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:h4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:i4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.vv(b.title||"")},ya:b.title},{I:"div",S:b.ND?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.S(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.qC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:h4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:i4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.vv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.S(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.qC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:i4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.vv(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:h4(b)}]};c=new g.S(c);var d=g.Qe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.dv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.BW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.qC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",Y:{dir:g.vv(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:i4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:h4(b)},{I:"div",S:"ytp-ce-expanding-icon",Y:Elb(b.iconUrl)}]};c=new g.S(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.qC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.vv(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:i4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:h4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.S(a)}b.isPlaceholder&&g.dv(c.element,"ytp-ce-placeholder");return c},h4=function(a){if(a.yV)var b=a.yV.thumbnails;
return Elb(b?b[b.length-1].url:null)},Elb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Dlb=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.dv(b.element,"ytp-ce-force-expand"),j4(a,c.id,!0)):(g.fv(b.element,"ytp-ce-force-expand"),g.fv(b.element,"ytp-ce-element-hover"),j4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){Flb(a,b,c)});
b.Qa("mouseleave",function(){Glb(a,b,c)});
a.player.U().B||b.Qa("click",function(){g.dv(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){Hlb(a,c,m)});
b.Qa("keypress",function(m){Hlb(a,c,m)});
b.Qa("focus",function(){Flb(a,b,c)});
b.Qa("blur",function(){Glb(a,b,c)});
b.Qa("touchstart",function(){Flb(a,b,c)});
var l=g.Se("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.fv(b.element,"ytp-ce-element-hover");g.fv(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.Se("ytp-sb-subscribe",b.element));d(g.Se("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},Hlb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.cv(d,"ytp-ce-element");){g.cv(d,"subscribe-label")&&Ilb(a,b);
if(g.cv(d,"ytp-ce-channel-subscribe"))return;d=g.tf(d)}if(!d||g.cv(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Glb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Vba)Ilb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.bo(i4(a,b.targetUrl)),g.xH(g.$d(c),void 0,b.sessionData);else{var e=g.DS(a.player.U())||a.player.getVideoData().Hf,f=function(){var h=i4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.ZB(h);e&&n&&(n.v||
n.list)?a.player.xo(n.v,l,n.list,!1,void 0,m||void 0):g.bxa(h,l)};
Ilb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},i4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.KS(a)+b}else return"";return b},Flb=function(a,b,c){g.cv(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.dv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Qu(function(){g.dv(b.element,"ytp-ce-element-hover")},200)).start():g.dv(b.element,"ytp-ce-element-hover"),k4(a,c.q7),j4(a,c.id,!0))},Glb=function(a,b,c){g.fv(b.element,"ytp-ce-element-hover");
g.fv(b.element,"ytp-ce-force-expand");j4(a,c.id,!1)},j4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.hv(a.j[e].element,"ytp-ce-element-shadow-show",c)},k4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||f4(a))c&&c();else{b=Jlb(a,b);var e=0,f=!1,h=new g.Qu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.EE(b[a],d)}},Ilb=function(a,b,c){k4(a,b.clickUrls,c);
(a=g.LF())&&b.D7&&g.jG(a,b.visualElement)},Jlb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Klb(b[d],c));return a},Klb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Llb=function(a){return"string"===typeof a?a:""},l4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Mlb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},m4=function(a){return a.value?a.value:null},n4=function(a){if(!a)return null;
var b=g.bo(Llb(a.value));b=g.$d(b);if(!b)return null;var c=l4(a.target,Nlb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Mlb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Olb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Rlb=function(a){if(!a)return null;
var b=l4(a.type,Plb),c=l4(a.trigger,Qlb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=n4(a?a:null);return b?new Olb(b,c,a):null},Slb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Tlb=function(a,b){return g.Eb(a.action,b)},Ulb=function(a,b){this.context=a;
this.j=b},Vlb=function(a){return a.customMessage?o4("div","iv-card-message",a.customMessage):""},p4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",Y:{style:a},V:c}},Wlb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(o4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},o4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.vv(c);return{I:a,Y:b,ya:c}},Xlb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.zC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.zC+");");c.dir=g.vv(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,Y:c,V:d}},q4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},Ylb=function(a,b){this.merchant=a;
this.price=b},Zlb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},$lb=function(a,b){return b?b:Zlb(a)?"current":"new"},r4=function(a,b){g.H.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Xa=new Map;this.Za=new Map;this.context.J.addEventListener(g.uK("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.vK("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},s4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.mL(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.qb=!1});
a.context.j.Qa(b,"touchmove",function(){a.qb=!0})},amb=function(a){var b;
return(null==(b=g.R(a,g.JG))?0:b.url)?g.R(a,g.JG).url:(a=g.R(a,g.AT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},t4=function(a,b,c){return{aX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
y_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
CK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},bmb=function(a,b,c){r4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Db=this.Na=this.Rb=this.C=this.isInitialized=!1;this.cards=[];this.tb=this.Z=this.La=this.G=this.Ua=this.j=null;this.ma=[];this.ra=this.N=this.Ff=this.Ga=null;this.K=0;this.Ea=new g.Qu(function(){},c.X.fl?4E3:3E3);
g.J(this,this.Ea);this.ib=new g.Qu(function(){});
g.J(this,this.ib);this.Ba=new Ulb(c,function(e,f,h,l,m,n){s4(d,e,f,h,l,m,n)});
this.W=new g.S({I:"div",S:"iv-drawer",Y:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.J(this,this.W);this.D=this.W.element;this.bb=new g.WG(this.W,330);g.J(this,this.bb);this.Jb=g.Se("iv-drawer-header-text",this.D);this.B=g.Se("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&u4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.C)&&v4(d)});
this.Sa=new g.gL(this);g.J(this,this.Sa);this.J.addEventListener("videodatachange",this.Ms.bind(this))},cmb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){u4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){v4(a)});
var c=b.headerText;g.vf(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.JF(b.trackingParams);a.N=g.JF(b.closeTrackingParams);a.Ff=g.JF(b.iconTrackingParams)},dmb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.xG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},Uo:null,Hj:e.trackingParams?g.JF(e.trackingParams):null,Ff:f&&f.trackingParams?g.JF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
zC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};w4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.xG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:x4(a,c,b,f),sponsored:!1,bj:t4(f,e,f.command),Uo:f.trackingParams?g.JF(f.trackingParams):null,Hj:e.trackingParams?g.JF(e.trackingParams):null,Ff:l&&l.trackingParams?g.JF(l.trackingParams):null,imageUrl:y4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.xG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,zC:null,title:f.title?g.xG(f.title):"",customMessage:f.callToAction?g.xG(f.callToAction):"",url:g.R(f.command,g.JG).url?n4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(f.command,g.JG).url}):null,onClickCommand:null};w4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.xG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,bj:t4(e,f,e.endpoint),Uo:e.trackingParams?g.JF(e.trackingParams):null,Hj:f.trackingParams?g.JF(f.trackingParams):null,Ff:l&&l.trackingParams?g.JF(l.trackingParams):null,channelId:g.R(e.endpoint,g.hV).browseId,customMessage:e.customText?g.xG(e.customText):null,profileImageUrl:y4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.xG(e.channelName):"",metaInfo:[e.subscriberCountText?g.xG(e.subscriberCountText):""],url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(e.endpoint,g.hV).canonicalBaseUrl?g.R(e.endpoint,g.hV).canonicalBaseUrl:"/channel/"+g.R(e.endpoint,g.hV).browseId}),onClickCommand:null};w4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.xG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,bj:t4(e,f,e.action),Uo:e.trackingParams?g.JF(e.trackingParams):null,Hj:f.trackingParams?g.JF(f.trackingParams):null,Ff:l&&l.trackingParams?g.JF(l.trackingParams):null,LF:y4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.xG(e.customMessage):null,playlistVideoCount:g.xG(e.playlistVideoCount),title:e.playlistTitle?g.xG(e.playlistTitle):"",metaInfo:[e.channelName?g.xG(e.channelName):
"",e.videoCountText?g.xG(e.videoCountText):""],url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:amb(e.action)}),onClickCommand:null};w4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.xG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,bj:t4(e,f,e.action),Uo:e.trackingParams?g.JF(e.trackingParams):null,Hj:f.trackingParams?g.JF(f.trackingParams):null,Ff:l&&l.trackingParams?g.JF(l.trackingParams):null,LF:y4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.xG(e.lengthString):null,customMessage:e.customMessage?g.xG(e.customMessage):null,title:e.videoTitle?g.xG(e.videoTitle):"",metaInfo:[e.channelName?g.xG(e.channelName):
"",e.viewCountText?g.xG(e.viewCountText):""],isLiveNow:!!e.badge,url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:amb(e.action)}),onClickCommand:null};w4(a,b)}}}}}a.K++},y4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},x4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},fmb=function(a,b){if(b=emb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.cg.id),g.sf(b.DM),g.Ib(a.cards,b),a.LG(),z4(a)},u4=function(a,b,c){if(!a.C){a.bb.show();
a.Ua=new g.Qu(function(){g.dv(a.context.J.getRootNode(),g.fZ.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Sa.T(a.B,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.LF();d&&a.Ga&&a.N&&g.hG(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.QX||(f.QX=!0,gmb(a.context.logger,f.cg.bj.aX,b)),d&&g.hG(d,[f.cg.Uo]);X3(a.J);c&&(a.G=new g.Qu(function(){a.La=a.Z;a.tb.focus()},330),a.G.start())}},v4=function(a){a.C&&(a.bb.hide(),g.$C(a.Sa),g.fv(a.context.J.getRootNode(),g.fZ.IV_DRAWER_OPEN),a.C=!1,X3(a.J),a.G&&a.G.stop(),a.G=new g.Qu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},imb=function(a){g.ev(a.Gb(),
[g.fZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.HU(a.J,a.D,5);hmb(a);a.Z=g.Se("ytp-cards-button",a.J.getRootNode());a.tb=g.Se("iv-drawer-close-button",a.D);a.isInitialized=!0},hmb=function(a){var b=g.Se("iv-drawer-close-button",a.D);
a.context.j.Qa(b,"click",a.d5,a);a.context.j.Qa(a.B,"touchend",function(){a.Ea.start()});
a.context.j.Qa(a.B,"scroll",a.A5,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.cv(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.SE("iv-button-shown",a.T7,a));a.ma.push(g.SE("iv-button-hidden",a.S7,a));jmb(a)},jmb=function(a){a.ma.push(g.SE("iv-teaser-shown",a.o1,a));
a.ma.push(g.SE("iv-teaser-hidden",a.U7,a));a.ma.push(g.SE("iv-teaser-clicked",a.n1,a));a.Db=!0},kmb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.R(b.onClickCommand,g.Ihb))?void 0:c.targetId)?(a.ra=b,!0):!1},lmb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.pRa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.R(h[0],g.A_a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},w4=function(a,b){if(!kmb(a,b)||lmb(a,b)){var c=mmb(a,b);
if(c){var d={cg:b,DM:c.element,QX:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Db||jmb(a),fmb(a,b.id),c=a.findLastIndex(d),g.Pb(a.cards,c,0,d));else{a.isInitialized||imb(a);fmb(a,b.id);var e=a.findLastIndex(d);g.Pb(a.cards,e,0,d);c.Ja(a.B,e);a.LG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,z4(a),nmb(a,d),u4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&omb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){omb(a,d)}),z4(a))}}},mmb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=Xlb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",Y:{href:b.url?m4(b.url)||"":""},V:[p4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[o4("h2",void 0,b.title),d]}]}]};c=new g.S(c);q4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],Y:{href:m4(b.url)||"","data-ytid":b.channelId},V:[p4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Vlb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},Wlb(b)]}]}]};c=new g.S(c);q4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",Y:{href:m4(b.url)||""},V:[p4(b.LF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Vlb(b),o4("h2","iv-card-primary-link",b.title),Wlb(b)]}]}]};
c=new g.S(c);q4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Xlb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?m4(b.url)||"":"";c={I:"div",Ma:c,Y:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",Y:{href:e},V:[o4("h2",d,b.title),f]}]}]};c=new g.S(c);d=g.ef("span");g.vf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Yd(d,"adInfo");q4(a,g.Re("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:m4(c))||""},V:[p4(b.LF,d),{I:"div",S:"iv-card-content",V:[Vlb(b),o4("h2","iv-card-primary-link",b.title),Wlb(b),f]}]}]};c=new g.S(e);q4(a,g.Re("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},pmb=function(a){if(a.j)return"productListing"===a.j.cg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.Br(a.cards,function(c){return"productListing"===c.cg.type})}return g.Br(a.cards,function(c){return"productListing"===c.cg.type})},z4=function(a){g.hv(a.J.getRootNode(),"ytp-cards-shopping-active",pmb(a))},omb=function(a,b){if(!g.cv(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.LF(),d=a.j?a.j.cg.Ff:a.Ff;
c&&d&&g.iG(c,[d]);a.j=b;z4(a)}(c=a.isInitialized&&"none"==a.Gb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.cg.teaserDurationMs&&a.J.YA(!0,{teaserText:b.cg.teaserText,durationMs:b.cg.teaserDurationMs,onClickCommand:b.cg.onClickCommand});a.ib.isActive()||((!a.C||!a.Ea.isActive()&&a.Na)&&nmb(a,b),a.ib.start(910+b.cg.teaserDurationMs))}},nmb=function(a,b){a.W.Ib?(b=new b4([0,
a.B.scrollTop],[0,b.DM.offsetTop],600,ulb),a.context.C.Qa(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Qa(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.tG(a.W,!0),a.B.scrollTop=b.DM.offsetTop,g.tG(a.W,!1))},A4=function(a){return a.j&&a.j.cg?a.j.cg:a.cards[0]&&a.cards[0].cg?a.cards[0].cg:null},emb=function(a,b){return g.Eb(a.cards,function(c){return c.cg.id===b})},B4=function(a,b,c){r4.call(this,a,b);
this.annotation=c;this.isActive=!1},qmb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},C4=function(a,b,c){B4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},rmb=function(a,b){var c=void 0===c?0:c;
var d=llb(b).width;g.os(b,d);c=new slb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,tlb);g.J(a,c);a.context.C.Qa(c,"begin",function(){g.vs(b,!0)});
c.play()},umb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.BW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.vs(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.is(l,"right",b.image_width+"px");g.pf(a.Gb(),l);a.C=new g.Qu(function(){smb(a,h,l)},500);
g.J(a,a.C);a.context.j.Qa(a.Gb(),"mouseover",function(){tmb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.Gb(),"mouseout",function(){a.C.start()})}},tmb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.us(b);a.j||(b.style.width=g.ns(f.width,!0),c.style.width=g.ns(f.width,!0));g.is(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.is(d,"right","1px");a.D=!0;g.vs(b,!0);a.G=new g.Qu(function(){g.dv(this.Gb(),"iv-branding-active")},0,a);
a.G.start()}},smb=function(a,b,c){g.fv(a.Gb(),"iv-branding-active");
a.K=new g.Qu(function(){g.vs(b,!1);a.j||(c.style.width=g.ns(0,!0))},250);
a.K.start();a.D=!1},vmb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},wmb=function(a,b,c){B4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.W=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Qu(function(){d.j.setAttribute("aria-hidden","true");g.vs(d.C,!1);g.vs(d.B,!0)},700,this);
g.J(this,this.G)},zmb=function(a,b,c){c.stopPropagation();
xmb(a);ymb(a,b);a.j.focus()},Amb=function(a){a.isCollapsed||a.Z||a.D||(g.dv(a.Gb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},xmb=function(a){a.G.stop();
a.isCollapsed&&(g.gv(a.Gb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.vs(a.B,!1),g.vs(a.C,!0))},ymb=function(a,b){a.D||(a.D=g.Zf(function(){Bmb(this);
Amb(this)},b,a))},Bmb=function(a){a.D&&(g.Ra.clearTimeout(a.D),a.D=null)},Cmb=function(a){this.J=a},gmb=function(a,b,c){b&&(c?D4(a,b.map(function(d){return g.Fu(d,c)})):D4(a,b))},D4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.EE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Dmb=function(a){g.UV.call(this,a);
var b=this;this.ma=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new Cmb(this.player);this.D=new g.gL(this);this.G=this.K=null;this.events=new g.gL(this);this.Pg=this.W=this.j=null;this.ra=[];g.J(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.q1,this);this.subscribe("resize",this.rJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.YY,this);g.J(this,this.events);this.Ba=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.S({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.B);g.HU(this.player,this.B.element,4);this.B.hide();this.C=new g.S({I:"div",Ma:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ba);this.C.element.appendChild(a);this.Ot()&&this.load();var c=this.createElement({I:"style"});(g.Pe("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.sf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Emb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.vs(a,!1);return a},Fmb=function(a,b){b=!b.isCued()&&!g.cH(b,1024);
g.tG(a.B,b);g.tG(a.C,b)},Gmb=function(a,b,c){a.Z=!0;
a.G=g.lC(b,c)},Hmb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.ab(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Hmb(a,e))}return c},Lmb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.fC(h)&&h.responseXML?h.responseXML:null)&&Imb(a,h)}};
g.sD()&&(d.onFinish=Jmb(a,d.onFinish));d.postParams={ic_only:"1"};Kmb(d,c);a.Z=!0;g.lC(b.Xa,d)}}},Kmb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.QG&&(a.postParams.ic_coll=b.QG);b.EM&&(a.postParams.ic_xml=b.EM);b.HK&&(a.postParams.ic_track=b.HK)},Mmb=function(a){var b=new g.S({I:"div"});
g.vs(b.element,!1);var c=new bmb(a.player,b.element,E4(a));g.J(c,b);b.Ja(a.B.element);c.yF();return c},Omb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ma=!0,Nmb(a,b),b.headerText&&a.Pg&&(c=g.xG(b.headerText),a.Pg.setAttribute("title",c))},E4=function(a){if(!a.W){var b=new vlb(a);
g.J(a,b);var c=new g.Ap(a);g.J(a,c);a.W=new vmb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.qj)}return a.W},Imb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.LF();if(e){var f=g.KF();f&&g.UB(g.Cva)(void 0,e,f,[g.JF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Hmb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=l4(f.type,Pmb),p=l4(f.style,Qmb),q=Llb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Rlb;if(null==t)var v=null;else if(g.$a(t)){l=[];for(var x=g.u(t),B=x.next();!B.done;B=x.next()){var F=f(B.value);
F&&l.push(F)}v=l}else{var G=f(t);v=G?[G]:[]}e=m&&n?new Slb(m,n,p,v,r):null}else e=null}catch(ta){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=Emb(f),L=null;switch(l.type){case "branding":if(f.player.U().xe)break;f.B.element.appendChild(I);L=new C4(I,E4(f),l);break;case "promotion":g.HU(f.player,I,4),L=new wmb(I,E4(f),l)}L&&L.yF();if(f=L)g.J(a,f),a.N[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Mmb(a),g.J(a,a.j));if("card"===e.type){I=a.j;var P=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(P)switch(f=e.tracking||{},f={aX:f.impression,click:f.click,close:f.close,y_:f.teaser_impression,CK:f.teaser_click},l=e.tracking_params||{},L=null,P){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Uo:l.card?g.JF(l.card):null,Hj:l.teaser?g.JF(l.teaser):null,Ff:l.icon?g.JF(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};w4(I,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,
Uo:l.card?g.JF(l.card):null,Hj:l.teaser?g.JF(l.teaser):null,Ff:l.icon?g.JF(l.icon):null,LF:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};w4(I,c);break;case "productListing":e.signin_url&&(L=n4({target:"current",value:e.signin_url}));P=[];for(var X=e.offers||[],ka=0;ka<X.length;ka++)P.push(new Ylb(g.Ae(X[ka].merchant),
g.Ae(X[ka].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Uo:l.card?g.JF(l.card):null,Hj:l.teaser?g.JF(l.teaser):null,Ff:l.icon?g.JF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,zC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Fmb:L,Emb:e.signin_title?e.signin_title:void 0,Dmb:e.signin_message?e.signin_message:void 0,offers:P,onClickCommand:null};w4(I,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Uo:l.card?g.JF(l.card):
null,Hj:l.teaser?g.JF(l.teaser):null,Ff:l.icon?g.JF(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,zC:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};w4(I,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,bj:f,Uo:l.card?g.JF(l.card):null,Hj:l.teaser?g.JF(l.teaser):null,Ff:l.icon?g.JF(l.icon):null,LF:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:n4({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},w4(I,c)}}else cmb(a.j,e);c=!0}}c&&
(X3(a.player),a.rJ())},Nmb=function(a,b){var c=!1;
a.j||(a.j=Mmb(a),g.J(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(dmb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.VT(f)||(c=a.j,d=b.headerText?g.xG(b.headerText):"",g.vf(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.JF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.JF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Ff=b.icon.infoCardIconRenderer.trackingParams?g.JF(b.icon.infoCardIconRenderer.trackingParams):null,a.rJ());X3(a.player)}},Rmb=function(a,b,c,d,e){if(!a.player.U().xe){var f=[];
b.navigationEndpoint&&g.R(b.navigationEndpoint,g.hV)&&g.R(b.navigationEndpoint,g.hV).browseId&&f.push(new Olb("openUrl","click",new Mlb("/channel/"+g.R(b.navigationEndpoint,g.hV).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.R(b.subscribeButton,
g.OT)){d.channel_id=g.R(b.subscribeButton,g.OT).channelId;var l;b=g.R(b.subscribeButton,g.OT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.xG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.xG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.xG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.xG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.R(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.P2))?void 0:m.url)||"";l={subscribeText:g.xG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.xG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Slb(c,"branding","branding",f,d);l=Emb(a);a.B.element.appendChild(l);f=new C4(l,E4(a),f);f.yF();g.J(f,f);a.N[c]=f}},Jmb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ra.push(g.Iu.Qi(function(){b.apply(null,g.na(c))}))}},Smb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.zU.prototype.YA=g.ca(29,function(a,b){var c=g.jW(this.Bb());c&&c.YA(a,b)});
var Z3={},$3=null;g.kb(b4,g.pv);g.k=b4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;a4(this);this.startTime=a=g.jb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.jJ();this.Ql("play");this.isPaused()&&this.Ql("resume");this.j=1;var b=g.eb(this);b in Z3||(Z3[b]=this);olb();plb(this,a);return!0};
g.k.stop=function(a){a4(this);this.j=0;a&&(this.progress=1);qlb(this,this.progress);this.Ql("stop");this.Wq()};
g.k.pause=function(){this.isPlaying()&&(a4(this),this.j=-1,this.Ql("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Ql("destroy");b4.Lf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.lL=function(){this.Ql("animate")};
g.k.Ql=function(a){this.dispatchEvent(new rlb(a,this))};
g.kb(rlb,g.zb);g.kb(c4,b4);c4.prototype.C=function(){};
c4.prototype.lL=function(){this.C();c4.Lf.lL.call(this)};
c4.prototype.Wq=function(){this.C();c4.Lf.Wq.call(this)};
c4.prototype.jJ=function(){this.C();c4.Lf.jJ.call(this)};
g.kb(slb,c4);slb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(vlb,g.H);g.k=vlb.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.fb)(c,d||this.B);a=g.UC(a,b,c);this.j.push(a);return a};
g.k.KI=function(a,b,c,d){c=(0,g.fb)(c,d||this.B);a=mlb(a,b,c);this.j.push(a);return a};
g.k.Oc=function(a){g.VC(a);g.Ib(this.j,a)};
g.k.Jf=function(){g.VC(this.j);this.j.length=0};
g.k.xa=function(){this.Jf();g.H.prototype.xa.call(this)};g.w(ylb,g.UV);g.k=ylb.prototype;g.k.load=function(){g.UV.prototype.load.call(this);if(!f4(this)){var a=g.SSa(this.player.getVideoData());a?(a=xlb(a,zlb(this)),g4(this,a,!1)):Alb(this)}};
g.k.unload=function(){g4(this,null);this.C&&(this.C.abort(),this.C=null);g.UV.prototype.unload.call(this)};
g.k.Eh=function(a,b){return f4(this)?"loadCustomEndscreenRenderer"===a?(a=xlb(b,"new"),g4(this,a),!0):null:null};
g.k.getOptions=function(){return f4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Zb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Tmb.length;f++){var h=Math.abs(b.width-Tmb[f]);if(-1===e||d>=h)e=f,d=h}d=Umb[e];this.B&&g.is(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.ts(e.element,m,f);g.os(e.element,n,p);g.gv(e.element,Vmb);256<m||256<f?g.dv(e.element,"ytp-ce-large-round"):96<m||96<f?g.dv(e.element,"ytp-ce-medium-round"):g.dv(e.element,"ytp-ce-small-round");g.gv(e.element,Wmb);m=h.left+h.width/2;h=h.top+l/2;g.dv(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.gv(e.element,Umb);g.dv(e.element,d);(e=g.Qe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.is(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())k4(this,this.endscreen.impressionUrls),(a=g.LF())&&this.endscreen.visualElement&&g.gG(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.dv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.dv(b,"ytp-ce-shown");k4(this,c.impressionUrls);(b=g.LF())&&g.gG(b,c.visualElement);this.player.U().K&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.fv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.fv(b,"ytp-ce-shown");this.player.U().K&&this.player.jb("endscreenelementhidden",a)}};
g.k.faa=function(a){var b=this;a.target===window&&(new g.Qu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.gv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Tmb=[346,426,470,506,570,640,853,1280,1920],Umb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Wmb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Vmb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Nlb={hta:"current",RTa:"new"};var Plb={CLOSE:"close",GXa:"openUrl",SUBSCRIBE:"subscribe"},Qlb={sra:"click",CLOSE:"close",PEa:"hidden",v2a:"rollOut",w2a:"rollOver",e4a:"shown"};Slb.prototype.gf=function(){var a=Tlb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Qmb={Zla:"anchored",H0:"branding",CHANNEL:"channel",Wsa:"cta",SEa:"highlightText",TIa:"label",PLAYLIST:"playlist",n_a:"popup",d7a:"speech",SUBSCRIBE:"subscribe",L$a:"title",VIDEO:"video",thb:"website"},Pmb={H0:"branding",fpa:"card",mva:"drawer",REa:"highlight",pPa:"marker",S0a:"promotion",TEXT:"text",Wib:"widget"};g.w(r4,g.H);g.k=r4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.tK(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.Za.set(a,e);this.context.J.qf([a])};
g.k.yF=function(){this.context.B.subscribe("resize",this.LG,this)};
g.k.Gb=function(){return this.element};
g.k.mL=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.sf(this.Gb())};
g.k.LG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=m4(a);if(f){var h=$lb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Hf||!1,n=g.ZB(f||"");m&&n&&(n.v||n.list)?e.context.J.xo(n.v,b,n.list,!1):g.xH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);D4(this.context.logger,c,l,d);Zlb(f)||(c=g.LF(),d=b.itct,c&&d&&g.jG(c,g.JF(d)))}};
g.k.xa=function(){this.Xa.clear();this.Za.clear();g.H.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.J(this,a);return a.element};g.w(bmb,r4);g.k=bmb.prototype;g.k.Ms=function(){this.ra&&w4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.us(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.LG=function(){var a=this.isAvailable();g.vs(this.Gb(),a);g.hv(this.context.J.getRootNode(),g.fZ.IV_DRAWER_ENABLED,a);X3(this.J)};
g.k.destroy=function(){this.J.YA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.TE(this.ma);g.$C(this.Sa);this.Ua&&this.Ua.dispose();this.G&&this.G.dispose();r4.prototype.destroy.call(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Fb(this.cards,function(c){return a.cg.startMs>c.cg.startMs||a.cg.startMs===c.cg.startMs&&a.cg.timestamp>=c.cg.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.d5=function(){if(this.C){D4(this.context.logger,A4(this).bj.close);var a=g.LF();a&&this.N&&g.jG(a,this.N);v4(this)}};
g.k.A5=function(){g.hv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.T7=function(){var a=g.LF(),b=A4(this);b=b?b.Ff:this.Ff;a&&b&&g.hG(a,[b])};
g.k.S7=function(){var a=g.LF(),b=A4(this);b=b?b.Ff:this.Ff;a&&b&&g.iG(a,[b])};
g.k.o1=function(){var a=A4(this);D4(this.context.logger,a.bj.y_);var b=g.LF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Hj&&c.push(a.Hj);a.Ff&&c.push(a.Ff);0<c.length&&g.hG(b,c)}else g.hG(b,[a.Hj,a.Ff])};
g.k.U7=function(){var a=g.LF(),b=A4(this);a&&b&&g.iG(a,[b.Hj])};
g.k.n1=function(a){var b=A4(this),c=g.LF();this.j?a?(a=this.context.logger,D4(a,b.bj.CK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Hj&&g.jG(c,b.Hj)):(a=this.context.logger,D4(a,b.bj.CK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ff&&g.jG(c,b.Ff)):(a=this.context.logger,D4(a,b.bj.CK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ff&&g.jG(c,this.Ff))};g.w(B4,r4);B4.prototype.yF=function(){r4.prototype.yF.call(this);qmb(this)};
B4.prototype.show=function(){r4.prototype.show.call(this);var a=g.LF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.hG(a,[g.JF(b.itct)])};
B4.prototype.hide=function(){r4.prototype.hide.call(this);var a=g.LF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.iG(a,[g.JF(b.itct)])};g.w(C4,B4);C4.prototype.PA=function(){g.dv(this.Gb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.vs(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Gb().appendChild(b);var c=this.annotation.gf();c&&s4(this,b,c,this.annotation.id,a.session_data);umb(this,a)};
C4.prototype.show=function(){if(!this.isActive&&(B4.prototype.show.call(this),this.N||(this.PA(),this.N=!0),g.vs(this.Gb(),!0),this.isActive=!0,this.B)){try{rmb(this,this.B)}catch(a){}g.dv(this.context.J.getRootNode(),"ytp-branding-shown")}};
C4.prototype.hide=function(){this.isActive&&(B4.prototype.hide.call(this),g.vs(this.Gb(),!1),this.isActive=!1,g.fv(this.context.J.getRootNode(),"ytp-branding-shown"))};
C4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);B4.prototype.destroy.call(this)};g.w(wmb,B4);g.k=wmb.prototype;
g.k.PA=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Gb().setAttribute("aria-hidden","true");this.Gb().setAttribute("aria-label","Promotion");this.Gb().tabIndex=0;var e=this.annotation.gf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&s4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.fo(f,m4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&s4(this,
this.Gb(),e,this.annotation.id,b.session_data,void 0,c)}g.dv(this.j,"iv-click-target");e&&s4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.dv(this.j,"iv-click-target"),e&&s4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Qa(this.B,"click",function(q){zmb(a,5E3,q)});
c.appendChild(this.B);g.vs(this.B,!1);this.context.j.Qa(this.Gb(),"mouseover",this.R6,this);this.context.j.Qa(this.Gb(),"mouseout",this.Q6,this);this.context.j.Qa(this.Gb(),"touchend",function(q){zmb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Qa(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.M6:this.L6,this);c.appendChild(this.C);g.ev(this.Gb(),d);h&&(g.pf(this.Gb(),h),n&&h.appendChild(n));g.pf(this.Gb(),this.N);g.pf(this.Gb(),c)};
g.k.show=function(){this.isActive||(B4.prototype.show.call(this),this.W||(this.PA(),this.W=!0),g.vs(this.Gb(),!0),g.Zf(function(){g.fv(this.Gb(),"iv-promo-inactive")},100,this),this.Gb().removeAttribute("aria-hidden"),this.isActive=!0,Bmb(this),xmb(this),ymb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.dv(this.Gb(),"iv-promo-inactive"),this.isActive=!1,this.Gb().setAttribute("aria-hidden","true"))};
g.k.mL=function(a,b,c,d,e,f){return this.isCollapsed?!1:B4.prototype.mL.call(this,a,b,c,d,e,f)};
g.k.R6=function(a){this.Z=!0;zmb(this,500,a)};
g.k.Q6=function(){this.Z=!1;Amb(this)};
g.k.L6=function(a){a.stopPropagation();this.hide()};
g.k.M6=function(a){a.stopPropagation();Bmb(this);this.isCollapsed=!0;g.dv(this.Gb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();B4.prototype.destroy.call(this)};g.w(Dmb,g.UV);g.k=Dmb.prototype;g.k.Eh=function(a,b){if(!Smb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.v2(b))&&Imb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(fmb(this.j,b),X3(this.player)),!0}return null};
g.k.getOptions=function(){return Smb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ot=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.iU(b)||g.sU(this.player.app)?!1:1===c&&!b.rU||a.Na.get(b.videoId)||g.WT(b)||g.TSa(b)?!0:!1};
g.k.rJ=function(){if(this.C){var a=this.player.rb().getVideoContentRect(!0);g.ts(this.C.element,a.width,a.height);g.os(this.C.element,a.left,a.top)}if(this.j){var b=this.player.hn();a=this.j;b=b.width;g.hv(a.D,"iv-drawer-small",426>=b);g.hv(a.D,"iv-drawer-big",1280<=b)}};
g.k.q1=function(a){Fmb(this,a.state);g.cH(a.state,2)&&(this.Ak()&&this.So()&&2!==this.player.getPresentingPlayerType()&&this.ZA(!1),this.YA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.fC(h)&&h.responseXML?h.responseXML:null)&&(Imb(b,h),g.dv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.UV.prototype.load.call(this);Fmb(this,this.player.Vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.sD()&&(a=Jmb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Kmb(e,f);f=f&&(f.EM||f.QG);if(!c.bx||f)c.Xa?Gmb(this,c.Xa,e):(this.K=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.VT(h))&&!b.ma&&Omb(b,h)},this.player.addEventListener("videodatachange",this.K));
g.HU(this.player,this.C.element,4);this.rJ();(f=g.WT(c))&&Nmb(this,f);(f=g.TSa(c))&&f.featuredChannel&&Rmb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Pg=g.Se("ytp-cards-button",this.player.getRootNode());g.VT(c)&&Omb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&Gmb(this,b.Xa,a)};
g.k.unload=function(){this.player.yf("annotations_module");for(var a=g.u(Object.keys(this.N)),b=a.next();!b.done;b=a.next())this.N[b.value].destroy();this.W=null;this.j&&(this.j.destroy(),this.j=null,X3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.ma=!1;this.N={};this.B.hide();g.UV.prototype.unload.call(this);this.C.detach();this.K&&(this.player.removeEventListener("videodatachange",this.K),this.K=null)};
g.k.YY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Lmb(this):this.load())};
g.k.Ak=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ma};
g.k.So=function(){return!!this.j&&this.j.C};
g.k.ZA=function(a,b,c){b=void 0===b?!1:b;this.Ak();this.j&&(a?c?u4(this.j,c,b):u4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):v4(this.j))};
g.k.YA=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.YY,this);g.fv(this.player.getRootNode(),g.fZ.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Iu,c=0,d=a.length;c<d;c++)b.Kj(a[c]);this.ra.length=0;g.UV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.S(a);g.J(this,a);return a.element};g.TV("annotations_module",Dmb);g.TV("creatorendscreen",ylb);})(_yt_player);
