(function(g){var window=this;'use strict';var isb=function(a,b){g.S.call(this,{I:"button",Ma:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],Y:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",Y:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",Y:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",Y:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",Y:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.Qa("click",this.onClick,this);this.updateValue("title",g.yU(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.wU(b.Le(),this.element))},jsb=function(a){g.S.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.ph);this.T(a,"onStateChange",this.S1)},ksb=function(a){g.UV.call(this,a);
this.B=new g.gL(this);this.j=new jsb(this.player);this.j.hide();g.HU(this.player,this.j.element,4);a.gg()&&(this.load(),g.hv(a.getRootNode(),"ytp-player-minimized",!0))};
g.w(isb,g.S);isb.prototype.onClick=function(){this.J.jb("onExpandMiniplayer")};g.w(jsb,g.S);g.k=jsb.prototype;
g.k.show=function(){this.j=new g.Ou(this.Q1,null,this);this.j.start();if(!this.G){this.tooltip=new g.fY(this.player,this);g.J(this,this.tooltip);g.HU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Rd=new g.xW(this.player);g.J(this,this.Rd);this.B=new g.S({I:"div",S:"ytp-miniplayer-scrim"});g.J(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.FS);var a=new g.S({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.BG()]});g.J(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.ES);a=new isb(this.player,this);g.J(this,a);a.Ja(this.B.element);this.C=new g.S({I:"div",S:"ytp-miniplayer-controls"});g.J(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.FS);var b=new g.S({I:"div",S:"ytp-miniplayer-button-container"});g.J(this,b);b.Ja(this.C.element);a=new g.S({I:"div",S:"ytp-miniplayer-play-button-container"});g.J(this,a);a.Ja(this.C.element);var c=new g.S({I:"div",S:"ytp-miniplayer-button-container"});
g.J(this,c);c.Ja(this.C.element);this.N=new g.tX(this.player,this,!1);g.J(this,this.N);this.N.Ja(b.element);b=new g.sX(this.player,this);g.J(this,b);b.Ja(a.element);this.nextButton=new g.tX(this.player,this,!0);g.J(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.ZX(this.player,this);g.J(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.yX(this.player,this);g.J(this,this.progressBar);g.HU(this.player,this.progressBar.element,4);this.D=new g.S({I:"div",S:"ytp-miniplayer-buttons"});
g.J(this,this.D);g.HU(this.player,this.D.element,4);a=new g.S({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.BG()]});g.J(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.ES);a=new g.S({I:"button",Ma:["ytp-miniplayer-replay-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.kwa()]});g.J(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.i$);this.T(this.player,"presentingplayerstatechange",this.R1);this.T(this.player,"appresize",this.Zb);
this.T(this.player,"fullscreentoggled",this.Zb);this.Zb();this.G=!0}0!==this.player.getPlayerState()&&g.S.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.hide.call(this);this.player.gg()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.xa.call(this)};
g.k.ES=function(){this.player.stopVideo();this.player.jb("onCloseMiniplayer")};
g.k.i$=function(){this.player.playVideo()};
g.k.FS=function(a){if(a.target===this.B.element||a.target===this.C.element)g.ZL(this.player.Vb())?this.player.pauseVideo():this.player.playVideo()};
g.k.ph=function(){g.hv(this.player.getRootNode(),"ytp-player-minimized",this.player.gg())};
g.k.Vf=function(){this.progressBar.Lc();this.K.Lc()};
g.k.Q1=function(){this.Vf();this.j&&this.j.start()};
g.k.R1=function(a){g.cH(a.state,32)&&this.tooltip.hide()};
g.k.Zb=function(){g.U_a(this.progressBar,0,this.player.rb().getPlayerSize().width,!1);g.zX(this.progressBar)};
g.k.S1=function(a){this.player.gg()&&(0===a?this.hide():this.show())};
g.k.Le=function(){return this.tooltip};
g.k.Et=function(a,b,c,d,e){var f=0,h=d=0,l=g.us(a);if(b){c=g.cv(b,"ytp-prev-button")||g.cv(b,"ytp-next-button");var m=g.cv(b,"ytp-play-button"),n=g.cv(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.rs(b,this.element),h=b.x,f=b.y-12):n&&(h=g.cv(b,"ytp-miniplayer-button-top-left"),f=g.rs(b,this.element),b=g.us(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.rb().getPlayerSize().width;e=f+(e||0);l=g.je(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.w(ksb,g.UV);g.k=ksb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.hv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.UV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.jl=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.TV("miniplayer",ksb);})(_yt_player);
